### ISSUE TITLE
No need for `-main` flag

### ISSUE THREAD

**Issue by cenkalti** [pablo-ruth/go-init#3]
`os.Args` can be used directly as main command.

The advantage of this that you can create a base image with:
```
ENTRYPOINT ["/bin/go-init", "-pre", "echo starting..."]
```

Then you can use CMD as usual in derived images:
```
CMD ["echo", "foo"]
```

Otherwise, I have to pass the main command as single string which looks weird in my opinion.

**Comment by ecklm** [comment]
I think the `-main` flag is good for staying explicit. It makes the command more obvious to read.

Actually I think to enable the `CMD` like yours would make go-init less comprehensive. Like for now, the whole main command must be in one string. You already split yours up to 2 in the `CMD`. To treat this would make `go-init` more obscure but not that much easier to use.

**Comment by cenkalti** [comment]
Another alternative is adding `--` and interpreting all arguments after that as main command.
https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

**Comment by ecklm** [comment]
Hm, that idea might actually work.

**Comment by pablo-ruth** [comment]
Hi,
I'm sorry, as mentioned in the Readme, I don't maintain this project anymore. Please feel free to fork!
